=== bchantech/ZumaBlitzRemake/schemas/config/loadlist.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "description": "The root entry.",
    "properties": {
        "$schema": true,
        "images": {
            "type": "array",
            "description": "A list of Images to be loaded.",
            "items": {
                "$ref": "../_structures/Image.json",
                "description": "A single image."
            }
        },
        "sprites": {
            "type": "array",
            "description": "A list of Sprites to be loaded.",
            "items": {
                "$ref": "../_structures/Sprite.json",
                "description": "A single sprite."
            }
        },
        "sounds": {
            "type": "array",
            "description": "A list of Sounds to be loaded.",
            "items": {
                "$ref": "../_structures/Sound.json",
                "description": "A single sound."
            }
        },
        "sound_events": {
            "type": "array",
            "description": "A list of Sound Events to be loaded.",
            "items": {
                "$ref": "../_structures/SoundEvent.json",
                "description": "A single sound event."
            }
        },
        "music": {
            "type": "array",
            "description": "A list of Music Tracks to be loaded.",
            "items": {
                "$ref": "../_structures/Music.json",
                "description": "A single music track."
            }
        },
        "colorPalettes": {
            "type": "array",
            "description": "A list of Color Palettes to be loaded. This field must contain all Color Palettes, as they cannot be loaded later - they all must be explicitly specified here.",
            "items": {
                "$ref": "../_structures/ColorPalette.json",
                "description": "A single Color Palette."
            }
        },
        "ui2AnimationConfigs": {
            "type": "array",
            "description": "A list of UI2 Animations to be loaded.",
            "items": {
                "$ref": "../_structures/UI2Animation.json",
                "description": "A single UI2 Animation."
            }
        },
        "ui2NodeConfigs": {
            "type": "array",
            "description": "A list of UI2 Nodes to be loaded.",
            "items": {
                "$ref": "../_structures/UI2Node.json",
                "description": "A single UI2 Node."
            }
        },
        "ui2SequenceConfigs": {
            "type": "array",
            "description": "A list of UI2 Sequences to be loaded.",
            "items": {
                "$ref": "../_structures/UI2Sequence.json",
                "description": "A single UI2 Sequence."
            }
        }
    },
    "additionalProperties": false
}

=== bchantech/ZumaBlitzRemake/games/ZumaBlitzRemake/config/loadlist.json
{
    "images": [
        "images/splash/background.png",
        "images/splash/disclaimer.png",
        "images/splash/loadingpie_unfilled.png",
        "images/splash/loadingpie_filled.png",
        "images/splash/loadingpie_overlay.png",
        "images/splash/logo.png"
    ],
    "sprites": [
        "sprites/splash/background.json",
        "sprites/splash/disclaimer.json",
        "sprites/splash/loadingpie_unfilled.json",
        "sprites/splash/loadingpie_filled.json",
        "sprites/splash/loadingpie_overlay.json",
        "sprites/splash/logo.json"
    ],
    "sounds": [
        "sounds/button_highlight.ogg"
    ],
    "sound_events": [
        "sound_events/button_hover.json"
    ],
    "music": [
        "music/MenuMusic.ogg",
        "music/GameMusic1.ogg",
        "music/GameMusic2.ogg",
        "music/GameMusic3.ogg",
        "music/15toGoMusic_1.ogg",
        "music/15toGoMusic_2.ogg"
    ],
    "colorPalettes": [
        "images/particles/wild_pal.png"
    ]
}
